apiVersion: apps/v1
kind: Deployment
metadata:
  name: pub-in-svc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pub-in-svc
  template:
    metadata:
      labels:
        app: pub-in-svc
    spec:
      containers:
        - name: koa
          image: rodrigodiez/pubin-api:${CIRCLE_SHA1}
          ports:
            - containerPort: 8080
          env:
            - name: ES_CLUSTER
              valueFrom:
                configMapKeyRef:
                  name: elasticsearch
                  key: cluster
            - name: ES_INDEX
              valueFrom:
                configMapKeyRef:
                  name: pub-in-svc
                  key: esIndex
            - name: ES_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: pub-in-svc
                  key: esAccessKey
            - name: ES_ACCESS_SECRET
              valueFrom:
                secretKeyRef:
                  name: pub-in-svc
                  key: esAccessSecret
            - name: KOA_PORT
              valueFrom:
                configMapKeyRef:
                  name: pub-in-svc
                  key: koaPort
